### ISSUE TITLE
2주차 Code Review

### ISSUE THREAD

**Issue by khodid** [hawking74/Moning#1]
https://github.com/hawking74/Moning/blob/1c7227d8a9e908f38e757e1c9b3640b338e49346/Lab%2006.%20Softmax%20training.py#L135-L176

``` python
 class SoftmaxClassifierModel(nn.Module): 
     def __init__(self): 
         super().__init__() 
         self.linear = nn.Linear(4,3)  #4 input to 3 class  
      
     def foward(self,x): 
         return self.linear(x) 

```

Lab 06번 실습에서  Error를 못 고치신 것 같아서 한 번 살펴봤습니다.

에러 메세지를 보니 model의 def: forward 가 문제인 것 같아 
꼼꼼히 읽어보니깐 오타가 있었네요.
클래스 정의에서 foward -> forward로 수정하면 결과 제대로 나옵니다 ㅎㅎ.

---

그 외에는 필기도 깔끔하게 들어갈 내용 다 있고,
코드도 가독성있게 잘 정리하셨네요.
본인만의 변수명으로 코드를 조금씩 고쳐가며 실습을 하신 게 인상깊었습니다.
자극 받고 갑니다!

**Comment by hawking74** [comment]
에러 위치가 안떠서 고민하고 있었는데 찾아주셔서 감사합니다!
-----Original Message-----
